### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by jonathanR79** [eminos/eminos-instagram-feed#2]
Hi,

Thanks this is working like a charm on my koken site https://www.jr-photo.be/pages/instagram/ but would you consider new features?

This page is done with the "Instagram Feed" WP plugin:
https://blog.jr-photo.be/instagram/

Would it be possible to get the profile description on top of the feed in your plugin as well?

Kind regards

**Comment by eminos** [comment]
Sure! I'll implement this.

**Comment by BlackSkorpio** [comment]
Could you make it optional to show the "normal" `{{ site.title }} {{ language.on }} Instagram` or the "Instagram version"?

**Comment by eminos** [comment]
@BlackSkorpio, could you please elaborate? I'm not sure I understand.
The feature @jonathanR79 suggested would be optional through the Koken plugin settings.

**Comment by BlackSkorpio** [comment]
At the moment in OxyGen I have been "forced" to wrap your plugin inside a wrapper with the header like this
![image](https://user-images.githubusercontent.com/11587201/37792910-63c397bc-2e0d-11e8-9ad1-b834e0abbf51.png)
This uses the koken code: `{{ site.title }} {{language.on }} Instagram`

And this could be the other choice (The info from IG)
![image](https://user-images.githubusercontent.com/11587201/37792954-8ef3013e-2e0d-11e8-8a64-f00f7faa2c63.png)

**Comment by eminos** [comment]
I have added an optional "Profile section" to just released version 1.1.0.

I think this plugin should be as simple as possible really, in terms of styling and so on.
So, @BlackSkorpio, I think that solution is perfect, to just add a heading above the Instagram feed. That way you can do whatever you want and style it however you want.

It's also possible to style the actual plugin/feed with custom CSS in Koken.
