### ISSUE TITLE
Adding native support in OxyGen and BackStage

### ISSUE THREAD

**Issue by BlackSkorpio** [eminos/eminos-instagram-feed#3]
Hi there @eminos very nice work here!
I'm currently adding support for your version of the Instagram Feed in to both my premium themes: [OxyGen ](https://oxygen.kokensupport.com) and [BackStage.](https://backstage.kokensupport.com)

**Comment by eminos** [comment]
Coolt! Lycka till :)

**Comment by BlackSkorpio** [comment]
LMFAO!!!!
So your "yet another Swede"!

Kommer strax en "live preview" på min site....
När vi kommit överens om titelupplägget LOL

**Comment by BlackSkorpio** [comment]
So far in OxyGen ;)
![image](https://user-images.githubusercontent.com/11587201/37793209-3b4f2f5c-2e0e-11e8-9bd9-212d2a630bb6.png)

**Comment by BlackSkorpio** [comment]
OxyGens first implementation running 1.0 from master (not with the latest commits applied):
https://varoystrand.se/artiklar/2016/09/oxygen-is-now-available-in-the-koken-store/

For now it's only activated in the footer of the essays...

**Comment by eminos** [comment]
Looking good :)
